// JpnTextTables.cpp - GENERATED by tools/gen_jpn_text.py, do not edit by hand.
//
// Every text table the Japanese PC release (Biohazard.exe) holds in its own
// executable, decoded and written back as readable Japanese. STR_JP() encodes
// each string to FONT.TIM glyph bytes at compile time, and every entry here
// re-encodes to the exact bytes the original holds - checked two ways, by
// `python tools/jpn_msg_decode.py verify` and by the static_asserts in
// tools/test_str_jp.cpp.
//
//   global_messages_jpn          0x004CDE58  set_message_display 0x00491980
//   g_ItemNamePointersJpn        0x004CD388  message_item_name_lookup 0x00491440
//   g_UnknownItemNamePointersJpn 0x004CD548  (= the last 16 name entries)
//   g_ItemDescriptionsJpn        0x004C9370  set_item_description_message 0x00491A40
//
// The readers pick these over the USA tables when the JPN asset tree is
// selected (config.ini [Assets] Version=JPN), because the encoding only means
// anything against data\FONT.TIM.
//
// Item names end with 0x07, not 0x01: the message state machine reads that as
// "return from item name". STR_JP still appends its own 0x01 after it, exactly
// as STR() does for the USA names in MenuData.cpp; nothing reads past the 0x07.
#include "../Globals.h"
#include "PrintText.h"

// --------------------------------------------------------------------------
// global_messages_jpn (Biohazard.exe 0x004CDE58)
// --------------------------------------------------------------------------
static constexpr auto s_gmjp_4CD730 = STR_JP(u8"\\iを取りますか?\\c\\n\\q ");
static constexpr auto s_gmjp_4CD744 = STR_JP(u8"\\iを入手した");
static constexpr auto s_gmjp_4CD753 = STR_JP(u8"このままではアイテムを入手できない");  // このままではアイテムを入手できない
static constexpr auto s_gmjp_4CD768 = STR_JP(u8"\\iを使った");
static constexpr auto s_gmjp_4CD775 = STR_JP(u8"\\iを置きますか?\\c\\n\\q\\d\\x01");
static constexpr auto s_gmjp_4CD789 = STR_JP(u8"\\iを使いますか?\\c\\n\\q\\d\\x01");
static constexpr auto s_gmjp_4CD79D = STR_JP(u8"\\iを\\nファイルにとじました\\p\\x00\\d\\x01");
static constexpr auto s_gmjp_4CD7B3 = STR_JP(u8"もうこのカギは必要ないようだ\\nすてますか?\\c\\n\\q\\n");
static constexpr auto s_gmjp_4CD7D0 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00    \\s\\x02剣の形が刻まれている");
static constexpr auto s_gmjp_4CD7ED = STR_JP(u8"剣の形が刻まれている");  // 剣の形が刻まれている
static constexpr auto s_gmjp_4CD7FC = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00    \\s\\x02鎧の形が刻まれている");
static constexpr auto s_gmjp_4CD819 = STR_JP(u8"鎧の形が刻まれている");  // 鎧の形が刻まれている
static constexpr auto s_gmjp_4CD828 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00    \\s\\x02盾の形が刻まれている");
static constexpr auto s_gmjp_4CD845 = STR_JP(u8"盾の形が刻まれている");  // 盾の形が刻まれている
static constexpr auto s_gmjp_4CD854 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00    \\s\\x02兜の形が刻まれている");
static constexpr auto s_gmjp_4CD871 = STR_JP(u8"兜の形が刻まれている");  // 兜の形が刻まれている
static constexpr auto s_gmjp_4CD880 = STR_JP(u8"\\n\\s\\x00  \\s\\x02ドアは厳重にロックされている\\p\\x00\\n\\s\\x00    \\s\\x02右にプレートがある");
static constexpr auto s_gmjp_4CD8AE = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00  \\s\\x02ドアに“クローゼット”とある");
static constexpr auto s_gmjp_4CD8DB = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00  \\s\\x02プレートに“002”とある");
static constexpr auto s_gmjp_4CD907 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00  \\s\\x02プレートに“003”とある");
static constexpr auto s_gmjp_4CD933 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00   \\s\\x02ドアに“制御室”とある");
static constexpr auto s_gmjp_4CD961 = STR_JP(u8"\\n\\s\\x00      \\s\\x02“動力室”\\p\\x00\\n\\s\\x00  \\s\\x02ドアは厳重にロックされている");
static constexpr auto s_gmjp_4CD991 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている");
static constexpr auto s_gmjp_4CD9A5 = STR_JP(u8"\\n\\s\\x00  \\s\\x02向こうからカギがかかっている");
static constexpr auto s_gmjp_4CD9BD = STR_JP(u8"\\n\\s\\x00      \\s\\x02カギを外した");
static constexpr auto s_gmjp_4CD9D1 = STR_JP(u8"\\n\\s\\x00    \\s\\x02カギがかかっている\\p\\x00\\n\\s\\x00  \\s\\x02キーピックを使えば開きそうだ");
static constexpr auto s_gmjp_4CD9FE = STR_JP(u8"\\n\\s\\x00     \\s\\x02急がなくては!");
static constexpr auto s_gmjp_4CDA12 = STR_JP(u8"\\n\\s\\x00    \\s\\x02調べている時間はない");
static constexpr auto s_gmjp_4CDA2A = STR_JP(u8"\\n\\s\\x00   \\s\\x02机にカギがかかっている");
static constexpr auto s_gmjp_4CDA40 = STR_JP(u8"\\n\\s\\x00   \\s\\x02机にカギがかかっている\\p\\x00\\iを使いますか?\\c\\n\\q\\d\\x01");
static constexpr auto s_gmjp_4CDA6A = STR_JP(u8"\\n\\s\\x00      クリス・・・\\s\\x10\\p\\x30\\n \\s\\x00     クリス・・・\\s\\x02\\d\\x30");
static constexpr auto s_gmjp_4CDA90 = STR_JP(u8"\\s\\x02They have escaped\\ninto the mansion\\p\\x30where they thought\\nit was safe.\\p\\x30      Yet・・・\\d\\x30");
static constexpr auto s_gmjp_4CDAE6 = STR_JP(u8"\\s\\x00  \\s\\x02You have once\\n\\s\\x00  \\s\\x02again entered\\p\\x30\\s\\x00 \\s\\x02the world of\\n\\s\\x00 \\s\\x02survival horror.\\p\\x30\\s\\x00    \\s\\x02Good luck!\\d\\x30");
static constexpr auto s_gmjp_4CDB4D = STR_JP(u8"\\s\\x00   \\s\\x02Be smart!\\n\\s\\x00   \\s\\x02Fighting foes\\p\\x30\\s\\x00  \\s\\x02isn't the only\\n\\s\\x00  \\s\\x02way to survive\\p\\x30\\s\\x00   \\s\\x02this horror.\\d\\x40");
static constexpr auto s_gmjp_4CDBB5 = STR_JP(u8"\\n\\s\\x00    \\s\\x02古いタイプライターだ\\p\\x00\\s\\x00  \\s\\x02\\x05\\x01インクリボン\\x05\\x00があれば、\\n\\s\\x00  \\s\\x02調査状況をセーブできるのだが");
static constexpr auto s_gmjp_4CDBFB = STR_JP(u8"\\s\\x00   \\s\\x02古いタイプライターだ\\n\\s\\x00   \\s\\x02調査状況をセーブできます\\p\\x00\\x05\\x01インクリボン\\x05\\x00を使いますか?\\c ");
static constexpr auto s_gmjp_4CDC3D = STR_JP(u8"\\s\\x00   \\s\\x02古いタイプライターがある\\p\\x00\\s\\x00   \\s\\x02調査状況をセーブできます\\nセーブしますか?\\c ");
static constexpr auto s_gmjp_4CDC77 = STR_JP(u8"“002”と刻まれている");  // “002”と刻まれている
static constexpr auto s_gmjp_4CDC88 = STR_JP(u8"“003”と刻まれている");  // “003”と刻まれている
static constexpr auto s_gmjp_4CDC99 = STR_JP(u8"机を開けるカギのようだ");  // 机を開けるカギのようだ
static constexpr auto s_gmjp_4CDCA8 = STR_JP(u8"変わったマークが刻まれている");  // 変わったマークが刻まれている
static constexpr auto s_gmjp_4CDCBA = STR_JP(u8"特別なコーティングがされている\\nかなり重要なカギのようだ・・・");
static constexpr auto s_gmjp_4CDCDF = STR_JP(u8"どこかにクローゼットがあるはずだ");  // どこかにクローゼットがあるはずだ
static constexpr auto s_gmjp_4CDCF1 = STR_JP(u8"先が四角形になっている");  // 先が四角形になっている
static constexpr auto s_gmjp_4CDD02 = STR_JP(u8"先が六角形になっている");  // 先が六角形になっている
static constexpr auto s_gmjp_4CDD13 = STR_JP(u8"全て中身は白紙になっている\\n特別な使い方でもあるのだろうか・・・");
static constexpr auto s_gmjp_4CDD3E = STR_JP(u8"本の中にメダルが入っていた");  // 本の中にメダルが入っていた
static constexpr auto s_gmjp_4CDD50 = STR_JP(u8"植物を枯らすために用いられる除草剤だ");  // 植物を枯らすために用いられる除草剤だ
static constexpr auto s_gmjp_4CDD6B = STR_JP(u8"\\iがセットされている");
static constexpr auto s_gmjp_4CDD7C = STR_JP(u8"これはもう必要ないだろう");  // これはもう必要ないだろう
static constexpr auto s_gmjp_4CDD8C = STR_JP(u8"ここでまぜるのは危険だ");  // ここでまぜるのは危険だ
static constexpr auto s_gmjp_4CDD9B = STR_JP(u8"毒ガスが発生した!");  // 毒ガスが発生した!
static constexpr auto s_gmjp_4CDDA9 = STR_JP(u8"調合に失敗したようだ\\n消えてしまった");
static constexpr auto s_gmjp_4CDDC2 = STR_JP(u8"薬草を調合しますか?\\c ");
static constexpr auto s_gmjp_4CDDD4 = STR_JP(u8"調合しても意味がなさそうだ");  // 調合しても意味がなさそうだ
static constexpr auto s_gmjp_4CDDE7 = STR_JP(u8"これだけでは使えない");  // これだけでは使えない
static constexpr auto s_gmjp_4CDDF4 = STR_JP(u8"別の薬剤とまぜることができる");  // 別の薬剤とまぜることができる
static constexpr auto s_gmjp_4CDE07 = STR_JP(u8"ここでは使えない");  // ここでは使えない
static constexpr auto s_gmjp_4CDE43 = STR_JP(u8"今は使う必要もなさそうだ");  // 今は使う必要もなさそうだ

unsigned char* global_messages_jpn[64] = {
    (unsigned char*)s_gmjp_4CD730.bytes,      // [  0] /iを取りますか?/c / /q 
    (unsigned char*)s_gmjp_4CD744.bytes,      // [  1] /iを入手した
    (unsigned char*)s_gmjp_4CD753.bytes,      // [  2] このままではアイテムを入手できない
    (unsigned char*)s_gmjp_4CD768.bytes,      // [  3] /iを使った
    (unsigned char*)s_gmjp_4CD775.bytes,      // [  4] /iを置きますか?/c / /q
    (unsigned char*)s_gmjp_4CD789.bytes,      // [  5] /iを使いますか?/c / /q
    (unsigned char*)s_gmjp_4CD79D.bytes,      // [  6] /iを / ファイルにとじました/p/x00
    (unsigned char*)s_gmjp_4CD7B3.bytes,      // [  7] もうこのカギは必要ないようだ / すてますか?/c / /q / 
    (unsigned char*)s_gmjp_4CD7D0.bytes,      // [  8]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00   
    (unsigned char*)s_gmjp_4CD7FC.bytes,      // [  9]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00   
    (unsigned char*)s_gmjp_4CD828.bytes,      // [ 10]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00   
    (unsigned char*)s_gmjp_4CD854.bytes,      // [ 11]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00   
    (unsigned char*)s_gmjp_4CD880.bytes,      // [ 12]  / /s/x00  /s/x02ドアは厳重にロックされている/p/x00 / /s/x00
    (unsigned char*)s_gmjp_4CD8AE.bytes,      // [ 13]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00  /
    (unsigned char*)s_gmjp_4CD8DB.bytes,      // [ 14]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00  /
    (unsigned char*)s_gmjp_4CD907.bytes,      // [ 15]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00  /
    (unsigned char*)s_gmjp_4CD933.bytes,      // [ 16]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00   
    (unsigned char*)s_gmjp_4CD961.bytes,      // [ 17]  / /s/x00      /s/x02“動力室”/p/x00 / /s/x00  /s/
    (unsigned char*)s_gmjp_4CD991.bytes,      // [ 18]  / /s/x00    /s/x02カギがかかっている
    (unsigned char*)s_gmjp_4CD9A5.bytes,      // [ 19]  / /s/x00  /s/x02向こうからカギがかかっている
    (unsigned char*)s_gmjp_4CD9BD.bytes,      // [ 20]  / /s/x00      /s/x02カギを外した
    (unsigned char*)s_gmjp_4CD9D1.bytes,      // [ 21]  / /s/x00    /s/x02カギがかかっている/p/x00 / /s/x00  /
    (unsigned char*)s_gmjp_4CD9FE.bytes,      // [ 22]  / /s/x00     /s/x02急がなくては!
    (unsigned char*)s_gmjp_4CDA12.bytes,      // [ 23]  / /s/x00    /s/x02調べている時間はない
    (unsigned char*)s_gmjp_4CDA2A.bytes,      // [ 24]  / /s/x00   /s/x02机にカギがかかっている
    (unsigned char*)s_gmjp_4CDA40.bytes,      // [ 25]  / /s/x00   /s/x02机にカギがかかっている/p/x00/iを使いますか?/c
    (unsigned char*)s_gmjp_4CDA6A.bytes,      // [ 26]  / /s/x00      クリス・・・/s/x10/p/x30 /  /s/x00   
    (unsigned char*)s_gmjp_4CDA90.bytes,      // [ 27] /s/x02They have escaped / into the mansion/p/x
    (unsigned char*)s_gmjp_4CDAE6.bytes,      // [ 28] /s/x00  /s/x02You have once / /s/x00  /s/x02ag
    (unsigned char*)s_gmjp_4CDB4D.bytes,      // [ 29] /s/x00   /s/x02Be smart! / /s/x00   /s/x02Figh
    (unsigned char*)s_gmjp_4CDBB5.bytes,      // [ 30]  / /s/x00    /s/x02古いタイプライターだ/p/x00/s/x00  /s/
    (unsigned char*)s_gmjp_4CDBFB.bytes,      // [ 31] /s/x00   /s/x02古いタイプライターだ / /s/x00   /s/x02調査状
    (unsigned char*)s_gmjp_4CDC3D.bytes,      // [ 32] /s/x00   /s/x02古いタイプライターがある/p/x00/s/x00   /s/x
    (unsigned char*)s_gmjp_4CD7ED.bytes,      // [ 33] 剣の形が刻まれている
    (unsigned char*)s_gmjp_4CD819.bytes,      // [ 34] 鎧の形が刻まれている
    (unsigned char*)s_gmjp_4CD845.bytes,      // [ 35] 盾の形が刻まれている
    (unsigned char*)s_gmjp_4CD871.bytes,      // [ 36] 兜の形が刻まれている
    (unsigned char*)s_gmjp_4CDC77.bytes,      // [ 37] “002”と刻まれている
    (unsigned char*)s_gmjp_4CDC88.bytes,      // [ 38] “003”と刻まれている
    (unsigned char*)s_gmjp_4CDC99.bytes,      // [ 39] 机を開けるカギのようだ
    (unsigned char*)s_gmjp_4CDCA8.bytes,      // [ 40] 変わったマークが刻まれている
    (unsigned char*)s_gmjp_4CDCBA.bytes,      // [ 41] 特別なコーティングがされている / かなり重要なカギのようだ・・・
    (unsigned char*)s_gmjp_4CDCDF.bytes,      // [ 42] どこかにクローゼットがあるはずだ
    (unsigned char*)s_gmjp_4CDCF1.bytes,      // [ 43] 先が四角形になっている
    (unsigned char*)s_gmjp_4CDD02.bytes,      // [ 44] 先が六角形になっている
    (unsigned char*)s_gmjp_4CDD13.bytes,      // [ 45] 全て中身は白紙になっている / 特別な使い方でもあるのだろうか・・・
    (unsigned char*)s_gmjp_4CDD3E.bytes,      // [ 46] 本の中にメダルが入っていた
    (unsigned char*)s_gmjp_4CDD50.bytes,      // [ 47] 植物を枯らすために用いられる除草剤だ
    (unsigned char*)s_gmjp_4CDD6B.bytes,      // [ 48] /iがセットされている
    (unsigned char*)s_gmjp_4CDD7C.bytes,      // [ 49] これはもう必要ないだろう
    (unsigned char*)s_gmjp_4CDD8C.bytes,      // [ 50] ここでまぜるのは危険だ
    (unsigned char*)s_gmjp_4CDD9B.bytes,      // [ 51] 毒ガスが発生した!
    (unsigned char*)s_gmjp_4CDDA9.bytes,      // [ 52] 調合に失敗したようだ / 消えてしまった
    (unsigned char*)s_gmjp_4CDDC2.bytes,      // [ 53] 薬草を調合しますか?/c 
    (unsigned char*)s_gmjp_4CDDD4.bytes,      // [ 54] 調合しても意味がなさそうだ
    (unsigned char*)s_gmjp_4CDDE7.bytes,      // [ 55] これだけでは使えない
    (unsigned char*)s_gmjp_4CDE07.bytes,      // [ 56] ここでは使えない
    (unsigned char*)s_gmjp_4CDDF4.bytes,      // [ 57] 別の薬剤とまぜることができる
    (unsigned char*)s_gmjp_4CDE07.bytes,      // [ 58] ここでは使えない
    (unsigned char*)s_gmjp_4CDE07.bytes,      // [ 59] ここでは使えない
    (unsigned char*)s_gmjp_4CDE07.bytes,      // [ 60] ここでは使えない
    (unsigned char*)s_gmjp_4CDE07.bytes,      // [ 61] ここでは使えない
    (unsigned char*)s_gmjp_4CDE43.bytes,      // [ 62] 今は使う必要もなさそうだ
    NULL,                          // [ 63]
};

// --------------------------------------------------------------------------
// g_ItemNamePointersJpn (0x004CD388), indexed by itemId - 1
// --------------------------------------------------------------------------
static constexpr auto s_injp_4CCFA0 = STR_JP(u8"コンバットナイフ\\x07");  // コンバットナイフ
static constexpr auto s_injp_4CCFA9 = STR_JP(u8"ベレッタ\\x07");  // ベレッタ
static constexpr auto s_injp_4CCFAE = STR_JP(u8"ショットガン\\x07");  // ショットガン
static constexpr auto s_injp_4CCFB5 = STR_JP(u8"コルトパイソン\\x07");  // コルトパイソン
static constexpr auto s_injp_4CCFBD = STR_JP(u8"火炎放射器\\x07");  // 火炎放射器
static constexpr auto s_injp_4CCFC8 = STR_JP(u8"グレネードガン\\x07");  // グレネードガン
static constexpr auto s_injp_4CCFD0 = STR_JP(u8"ロケットランチャー\\x07");  // ロケットランチャー
static constexpr auto s_injp_4CCFDA = STR_JP(u8"ベレッタのマガジン\\x07");  // ベレッタのマガジン
static constexpr auto s_injp_4CCFE4 = STR_JP(u8"ショットガンの弾\\x07");  // ショットガンの弾
static constexpr auto s_injp_4CCFEE = STR_JP(u8"ダムダム弾\\x07");  // ダムダム弾
static constexpr auto s_injp_4CCFF5 = STR_JP(u8"マグナム弾\\x07");  // マグナム弾
static constexpr auto s_injp_4CCFFC = STR_JP(u8"火炎放射器の燃料\\x07");  // 火炎放射器の燃料
static constexpr auto s_injp_4CD00C = STR_JP(u8"グレネード弾\\x07");  // グレネード弾
static constexpr auto s_injp_4CD014 = STR_JP(u8"硫酸弾\\x07");  // 硫酸弾
static constexpr auto s_injp_4CD01B = STR_JP(u8"火炎弾\\x07");  // 火炎弾
static constexpr auto s_injp_4CD022 = STR_JP(u8"空ビン\\x07");  // 空ビン
static constexpr auto s_injp_4CD027 = STR_JP(u8"水\\x07");  // 水
static constexpr auto s_injp_4CD02A = STR_JP(u8"UMB No.2\\x07");  // UMB No.2
static constexpr auto s_injp_4CD034 = STR_JP(u8"UMB No.4\\x07");  // UMB No.4
static constexpr auto s_injp_4CD03E = STR_JP(u8"UMB No.7\\x07");  // UMB No.7
static constexpr auto s_injp_4CD048 = STR_JP(u8"UMB No.13\\x07");  // UMB No.13
static constexpr auto s_injp_4CD053 = STR_JP(u8"YelloWー6\\x07");  // YelloWー6
static constexpr auto s_injp_4CD05C = STR_JP(u8"NPー003\\x07");  // NPー003
static constexpr auto s_injp_4CD063 = STR_JP(u8"VーJOLT\\x07");  // VーJOLT
static constexpr auto s_injp_4CD06A = STR_JP(u8"壊れたショットガン\\x07");  // 壊れたショットガン
static constexpr auto s_injp_4CD075 = STR_JP(u8"クランク\\x07");  // クランク
static constexpr auto s_injp_4CD07A = STR_JP(u8"四角クランク\\x07");  // 四角クランク
static constexpr auto s_injp_4CD083 = STR_JP(u8"六角クランク\\x07");  // 六角クランク
static constexpr auto s_injp_4CD08C = STR_JP(u8"エンブレム\\x07");  // エンブレム
static constexpr auto s_injp_4CD092 = STR_JP(u8"ゴールドエンブレム\\x07");  // ゴールドエンブレム
static constexpr auto s_injp_4CD09C = STR_JP(u8"青い宝石\\x07");  // 青い宝石
static constexpr auto s_injp_4CD0A4 = STR_JP(u8"赤い宝石\\x07");  // 赤い宝石
static constexpr auto s_injp_4CD0AC = STR_JP(u8"楽譜\\x07");  // 楽譜
static constexpr auto s_injp_4CD0B1 = STR_JP(u8"オオカミのメダル\\x07");  // オオカミのメダル
static constexpr auto s_injp_4CD0BA = STR_JP(u8"オオワシのメダル\\x07");  // オオワシのメダル
static constexpr auto s_injp_4CD0C3 = STR_JP(u8"薬\\x07");  // 薬
static constexpr auto s_injp_4CD0C6 = STR_JP(u8"除草剤\\x07");  // 除草剤
static constexpr auto s_injp_4CD0CD = STR_JP(u8"バッテリー\\x07");  // バッテリー
static constexpr auto s_injp_4CD0D3 = STR_JP(u8"MOディスク\\x07");  // MOディスク
static constexpr auto s_injp_4CD0DA = STR_JP(u8"ウィンドクレスト\\x07");  // ウィンドクレスト
static constexpr auto s_injp_4CD0E3 = STR_JP(u8"信号弾\\x07");  // 信号弾
static constexpr auto s_injp_4CD0EA = STR_JP(u8"スライド\\x07");  // スライド
static constexpr auto s_injp_4CD0EF = STR_JP(u8"ムーンクレスト\\x07");  // ムーンクレスト
static constexpr auto s_injp_4CD0F7 = STR_JP(u8"スタークレスト\\x07");  // スタークレスト
static constexpr auto s_injp_4CD0FF = STR_JP(u8"サンクレスト\\x07");  // サンクレスト
static constexpr auto s_injp_4CD106 = STR_JP(u8"インクリボン\\x07");  // インクリボン
static constexpr auto s_injp_4CD10D = STR_JP(u8"ライター\\x07");  // ライター
static constexpr auto s_injp_4CD112 = STR_JP(u8"キーピック\\x07");  // キーピック
static constexpr auto s_injp_4CD118 = STR_JP(u8"オイル\\x07");  // オイル
static constexpr auto s_injp_4CD11C = STR_JP(u8"館のカギ\\x07");  // 館のカギ
static constexpr auto s_injp_4CD122 = STR_JP(u8"剣のカギ\\x07");  // 剣のカギ
static constexpr auto s_injp_4CD128 = STR_JP(u8"鎧のカギ\\x07");  // 鎧のカギ
static constexpr auto s_injp_4CD12E = STR_JP(u8"盾のカギ\\x07");  // 盾のカギ
static constexpr auto s_injp_4CD134 = STR_JP(u8"兜のカギ\\x07");  // 兜のカギ
static constexpr auto s_injp_4CD13A = STR_JP(u8"マスターキー\\x07");  // マスターキー
static constexpr auto s_injp_4CD141 = STR_JP(u8"クローゼットのカギ\\x07");  // クローゼットのカギ
static constexpr auto s_injp_4CD14B = STR_JP(u8"寄宿舎のカギ\\x07");  // 寄宿舎のカギ
static constexpr auto s_injp_4CD155 = STR_JP(u8"002号室のカギ\\x07");  // 002号室のカギ
static constexpr auto s_injp_4CD160 = STR_JP(u8"003号室のカギ\\x07");  // 003号室のカギ
static constexpr auto s_injp_4CD16B = STR_JP(u8"制御室のカギ\\x07");  // 制御室のカギ
static constexpr auto s_injp_4CD175 = STR_JP(u8"動力室のカギ\\x07");  // 動力室のカギ
static constexpr auto s_injp_4CD17F = STR_JP(u8"小さなカギ\\x07");  // 小さなカギ
static constexpr auto s_injp_4CD186 = STR_JP(u8"机のカギ\\x07");  // 机のカギ
static constexpr auto s_injp_4CD18C = STR_JP(u8"研究所のカギ\\x07");  // 研究所のカギ
static constexpr auto s_injp_4CD196 = STR_JP(u8"スペシャルキー\\x07");  // スペシャルキー
static constexpr auto s_injp_4CD19E = STR_JP(u8"赤い本\\x07");  // 赤い本
static constexpr auto s_injp_4CD1A4 = STR_JP(u8"白紙の本\\x07");  // 白紙の本
static constexpr auto s_injp_4CD1AC = STR_JP(u8"最後の書(下)\\x07");  // 最後の書(下)
static constexpr auto s_injp_4CD1BA = STR_JP(u8"最後の書(上)\\x07");  // 最後の書(上)
static constexpr auto s_injp_4CD1C8 = STR_JP(u8"救急用スプレー\\x07");  // 救急用スプレー
static constexpr auto s_injp_4CD1D3 = STR_JP(u8"血清\\x07");  // 血清
static constexpr auto s_injp_4CD1D8 = STR_JP(u8"レッドハーブ\\x07");  // レッドハーブ
static constexpr auto s_injp_4CD1DF = STR_JP(u8"グリーンハーブ\\x07");  // グリーンハーブ
static constexpr auto s_injp_4CD1E7 = STR_JP(u8"ブルーハーブ\\x07");  // ブルーハーブ
static constexpr auto s_injp_4CD1EE = STR_JP(u8"調合したハーブ\\x07");  // 調合したハーブ
static constexpr auto s_injp_4CD1F8 = STR_JP(u8"ピッケル\\x07");  // ピッケル
static constexpr auto s_injp_4CD1FD = STR_JP(u8"通信機\\x07");  // 通信機
static constexpr auto s_injp_4CD204 = STR_JP(u8"館1Fの地図\\x07");  // 館1Fの地図
static constexpr auto s_injp_4CD20E = STR_JP(u8"館2Fの地図\\x07");  // 館2Fの地図
static constexpr auto s_injp_4CD218 = STR_JP(u8"中庭の地図\\x07");  // 中庭の地図
static constexpr auto s_injp_4CD222 = STR_JP(u8"中庭地下の地図\\x07");  // 中庭地下の地図
static constexpr auto s_injp_4CD230 = STR_JP(u8"寄宿舎の地図\\x07");  // 寄宿舎の地図
static constexpr auto s_injp_4CD23C = STR_JP(u8"研究所の地図\\x07");  // 研究所の地図
static constexpr auto s_injp_4CD248 = STR_JP(u8"\\xFA\\x3B待状\\x07");
static constexpr auto s_injp_4CD24F = STR_JP(u8"未状\\x07");  // 未状
static constexpr auto s_injp_4CD254 = STR_JP(u8"トレヴァーの手記(1)\\x07");  // トレヴァーの手記(1)
static constexpr auto s_injp_4CD264 = STR_JP(u8"トレヴァーの手記(2)\\x07");  // トレヴァーの手記(2)
static constexpr auto s_injp_4CD274 = STR_JP(u8"トレヴァーの手記(3)\\x07");  // トレヴァーの手記(3)
static constexpr auto s_injp_4CD284 = STR_JP(u8"トレヴァーの手記(4)\\x07");  // トレヴァーの手記(4)
static constexpr auto s_injp_4CD294 = STR_JP(u8"トレヴァーの手記(5)\\x07");  // トレヴァーの手記(5)
static constexpr auto s_injp_4CD2A4 = STR_JP(u8"トレヴァーの手記(6)\\x07");  // トレヴァーの手記(6)
static constexpr auto s_injp_4CD2B4 = STR_JP(u8"トレヴァーの手記(7)\\x07");  // トレヴァーの手記(7)
static constexpr auto s_injp_4CD2C4 = STR_JP(u8"トレヴァーの手記(8)\\x07");  // トレヴァーの手記(8)
static constexpr auto s_injp_4CD2D4 = STR_JP(u8"最後の手記\\x07");  // 最後の手記
static constexpr auto s_injp_4CD2DE = STR_JP(u8"研究員の遺書\\x07");  // 研究員の遺書
static constexpr auto s_injp_4CD2EA = STR_JP(u8"飼育係の日誌\\x07");  // 飼育係の日誌
static constexpr auto s_injp_4CD2F6 = STR_JP(u8"保安部長へのメール\\x07");  // 保安部長へのメール
static constexpr auto s_injp_4CD304 = STR_JP(u8"パスナンバー\\x07");  // パスナンバー
static constexpr auto s_injp_4CD30B = STR_JP(u8"プラント42のメモ\\x07");  // プラント42のメモ
static constexpr auto s_injp_4CD315 = STR_JP(u8"ファックス\\x07");  // ファックス
static constexpr auto s_injp_4CD31B = STR_JP(u8"スクラップブック\\x07");  // スクラップブック
static constexpr auto s_injp_4CD324 = STR_JP(u8"研究所・警備システム資料\\x07");  // 研究所・警備システム資料
static constexpr auto s_injp_4CD338 = STR_JP(u8"研究員の手紙\\x07");  // 研究員の手紙
static constexpr auto s_injp_4CD344 = STR_JP(u8"有機化学実験ファイル\\x07");  // 有機化学実験ファイル
static constexpr auto s_injp_4CD355 = STR_JP(u8"バリーの写真\\x07");  // バリーの写真
static constexpr auto s_injp_4CD35E = STR_JP(u8"パスコード01\\x07");  // パスコード01
static constexpr auto s_injp_4CD366 = STR_JP(u8"パスコード02\\x07");  // パスコード02
static constexpr auto s_injp_4CD36E = STR_JP(u8"パスコード03\\x07");  // パスコード03
static constexpr auto s_injp_4CD376 = STR_JP(u8"植物学\\x07");  // 植物学
static constexpr auto s_injp_4CD37D = STR_JP(u8"イングラム\\x07");  // イングラム
static constexpr auto s_injp_4CD383 = STR_JP(u8"ミニミ\\x07");  // ミニミ

extern const unsigned char* g_ItemNamePointersJpn[128] = {
    (unsigned char*)s_injp_4CCFA0.bytes,      // [  0] コンバットナイフ
    (unsigned char*)s_injp_4CCFA9.bytes,      // [  1] ベレッタ
    (unsigned char*)s_injp_4CCFAE.bytes,      // [  2] ショットガン
    (unsigned char*)s_injp_4CCFB5.bytes,      // [  3] コルトパイソン
    (unsigned char*)s_injp_4CCFB5.bytes,      // [  4] コルトパイソン
    (unsigned char*)s_injp_4CCFBD.bytes,      // [  5] 火炎放射器
    (unsigned char*)s_injp_4CCFC8.bytes,      // [  6] グレネードガン
    (unsigned char*)s_injp_4CCFC8.bytes,      // [  7] グレネードガン
    (unsigned char*)s_injp_4CCFC8.bytes,      // [  8] グレネードガン
    (unsigned char*)s_injp_4CCFD0.bytes,      // [  9] ロケットランチャー
    (unsigned char*)s_injp_4CCFDA.bytes,      // [ 10] ベレッタのマガジン
    (unsigned char*)s_injp_4CCFE4.bytes,      // [ 11] ショットガンの弾
    (unsigned char*)s_injp_4CCFEE.bytes,      // [ 12] ダムダム弾
    (unsigned char*)s_injp_4CCFF5.bytes,      // [ 13] マグナム弾
    (unsigned char*)s_injp_4CCFFC.bytes,      // [ 14] 火炎放射器の燃料
    (unsigned char*)s_injp_4CD00C.bytes,      // [ 15] グレネード弾
    (unsigned char*)s_injp_4CD014.bytes,      // [ 16] 硫酸弾
    (unsigned char*)s_injp_4CD01B.bytes,      // [ 17] 火炎弾
    (unsigned char*)s_injp_4CD022.bytes,      // [ 18] 空ビン
    (unsigned char*)s_injp_4CD027.bytes,      // [ 19] 水
    (unsigned char*)s_injp_4CD02A.bytes,      // [ 20] UMB No.2
    (unsigned char*)s_injp_4CD034.bytes,      // [ 21] UMB No.4
    (unsigned char*)s_injp_4CD03E.bytes,      // [ 22] UMB No.7
    (unsigned char*)s_injp_4CD048.bytes,      // [ 23] UMB No.13
    (unsigned char*)s_injp_4CD053.bytes,      // [ 24] YelloWー6
    (unsigned char*)s_injp_4CD05C.bytes,      // [ 25] NPー003
    (unsigned char*)s_injp_4CD063.bytes,      // [ 26] VーJOLT
    (unsigned char*)s_injp_4CD06A.bytes,      // [ 27] 壊れたショットガン
    (unsigned char*)s_injp_4CD07A.bytes,      // [ 28] 四角クランク
    (unsigned char*)s_injp_4CD083.bytes,      // [ 29] 六角クランク
    (unsigned char*)s_injp_4CD08C.bytes,      // [ 30] エンブレム
    (unsigned char*)s_injp_4CD092.bytes,      // [ 31] ゴールドエンブレム
    (unsigned char*)s_injp_4CD09C.bytes,      // [ 32] 青い宝石
    (unsigned char*)s_injp_4CD0A4.bytes,      // [ 33] 赤い宝石
    (unsigned char*)s_injp_4CD0AC.bytes,      // [ 34] 楽譜
    (unsigned char*)s_injp_4CD0B1.bytes,      // [ 35] オオカミのメダル
    (unsigned char*)s_injp_4CD0BA.bytes,      // [ 36] オオワシのメダル
    (unsigned char*)s_injp_4CD0C6.bytes,      // [ 37] 除草剤
    (unsigned char*)s_injp_4CD0CD.bytes,      // [ 38] バッテリー
    (unsigned char*)s_injp_4CD0D3.bytes,      // [ 39] MOディスク
    (unsigned char*)s_injp_4CD0DA.bytes,      // [ 40] ウィンドクレスト
    (unsigned char*)s_injp_4CD0E3.bytes,      // [ 41] 信号弾
    (unsigned char*)s_injp_4CD0EA.bytes,      // [ 42] スライド
    (unsigned char*)s_injp_4CD0EF.bytes,      // [ 43] ムーンクレスト
    (unsigned char*)s_injp_4CD0F7.bytes,      // [ 44] スタークレスト
    (unsigned char*)s_injp_4CD0FF.bytes,      // [ 45] サンクレスト
    (unsigned char*)s_injp_4CD106.bytes,      // [ 46] インクリボン
    (unsigned char*)s_injp_4CD10D.bytes,      // [ 47] ライター
    (unsigned char*)s_injp_4CD112.bytes,      // [ 48] キーピック
    (unsigned char*)s_injp_4CD118.bytes,      // [ 49] オイル
    (unsigned char*)s_injp_4CD122.bytes,      // [ 50] 剣のカギ
    (unsigned char*)s_injp_4CD128.bytes,      // [ 51] 鎧のカギ
    (unsigned char*)s_injp_4CD12E.bytes,      // [ 52] 盾のカギ
    (unsigned char*)s_injp_4CD134.bytes,      // [ 53] 兜のカギ
    (unsigned char*)s_injp_4CD13A.bytes,      // [ 54] マスターキー
    (unsigned char*)s_injp_4CD141.bytes,      // [ 55] クローゼットのカギ
    (unsigned char*)s_injp_4CD155.bytes,      // [ 56] 002号室のカギ
    (unsigned char*)s_injp_4CD160.bytes,      // [ 57] 003号室のカギ
    (unsigned char*)s_injp_4CD16B.bytes,      // [ 58] 制御室のカギ
    (unsigned char*)s_injp_4CD175.bytes,      // [ 59] 動力室のカギ
    (unsigned char*)s_injp_4CD186.bytes,      // [ 60] 机のカギ
    (unsigned char*)s_injp_4CD1A4.bytes,      // [ 61] 白紙の本
    (unsigned char*)s_injp_4CD1AC.bytes,      // [ 62] 最後の書(下)
    (unsigned char*)s_injp_4CD1BA.bytes,      // [ 63] 最後の書(上)
    (unsigned char*)s_injp_4CD1C8.bytes,      // [ 64] 救急用スプレー
    (unsigned char*)s_injp_4CD1D3.bytes,      // [ 65] 血清
    (unsigned char*)s_injp_4CD1D8.bytes,      // [ 66] レッドハーブ
    (unsigned char*)s_injp_4CD1DF.bytes,      // [ 67] グリーンハーブ
    (unsigned char*)s_injp_4CD1E7.bytes,      // [ 68] ブルーハーブ
    (unsigned char*)s_injp_4CD1EE.bytes,      // [ 69] 調合したハーブ
    (unsigned char*)s_injp_4CD1EE.bytes,      // [ 70] 調合したハーブ
    (unsigned char*)s_injp_4CD1EE.bytes,      // [ 71] 調合したハーブ
    (unsigned char*)s_injp_4CD1EE.bytes,      // [ 72] 調合したハーブ
    (unsigned char*)s_injp_4CD1EE.bytes,      // [ 73] 調合したハーブ
    (unsigned char*)s_injp_4CD1EE.bytes,      // [ 74] 調合したハーブ
    (unsigned char*)s_injp_4CD1F8.bytes,      // [ 75] ピッケル
    (unsigned char*)s_injp_4CD1FD.bytes,      // [ 76] 通信機
    (unsigned char*)s_injp_4CD204.bytes,      // [ 77] 館1Fの地図
    (unsigned char*)s_injp_4CD20E.bytes,      // [ 78] 館2Fの地図
    (unsigned char*)s_injp_4CD218.bytes,      // [ 79] 中庭の地図
    (unsigned char*)s_injp_4CD222.bytes,      // [ 80] 中庭地下の地図
    (unsigned char*)s_injp_4CD230.bytes,      // [ 81] 寄宿舎の地図
    (unsigned char*)s_injp_4CD23C.bytes,      // [ 82] 研究所の地図
    (unsigned char*)s_injp_4CD248.bytes,      // [ 83] /xFA/x3B待状
    (unsigned char*)s_injp_4CD24F.bytes,      // [ 84] 未状
    (unsigned char*)s_injp_4CD254.bytes,      // [ 85] トレヴァーの手記(1)
    (unsigned char*)s_injp_4CD264.bytes,      // [ 86] トレヴァーの手記(2)
    (unsigned char*)s_injp_4CD274.bytes,      // [ 87] トレヴァーの手記(3)
    (unsigned char*)s_injp_4CD284.bytes,      // [ 88] トレヴァーの手記(4)
    (unsigned char*)s_injp_4CD294.bytes,      // [ 89] トレヴァーの手記(5)
    (unsigned char*)s_injp_4CD2A4.bytes,      // [ 90] トレヴァーの手記(6)
    (unsigned char*)s_injp_4CD2B4.bytes,      // [ 91] トレヴァーの手記(7)
    (unsigned char*)s_injp_4CD2C4.bytes,      // [ 92] トレヴァーの手記(8)
    (unsigned char*)s_injp_4CD2D4.bytes,      // [ 93] 最後の手記
    (unsigned char*)s_injp_4CD2DE.bytes,      // [ 94] 研究員の遺書
    (unsigned char*)s_injp_4CD2DE.bytes,      // [ 95] 研究員の遺書
    (unsigned char*)s_injp_4CD2EA.bytes,      // [ 96] 飼育係の日誌
    (unsigned char*)s_injp_4CD2F6.bytes,      // [ 97] 保安部長へのメール
    (unsigned char*)s_injp_4CD304.bytes,      // [ 98] パスナンバー
    (unsigned char*)s_injp_4CD30B.bytes,      // [ 99] プラント42のメモ
    (unsigned char*)s_injp_4CD315.bytes,      // [100] ファックス
    (unsigned char*)s_injp_4CD31B.bytes,      // [101] スクラップブック
    (unsigned char*)s_injp_4CD324.bytes,      // [102] 研究所・警備システム資料
    (unsigned char*)s_injp_4CD338.bytes,      // [103] 研究員の手紙
    (unsigned char*)s_injp_4CD344.bytes,      // [104] 有機化学実験ファイル
    (unsigned char*)s_injp_4CD355.bytes,      // [105] バリーの写真
    (unsigned char*)s_injp_4CD35E.bytes,      // [106] パスコード01
    (unsigned char*)s_injp_4CD366.bytes,      // [107] パスコード02
    (unsigned char*)s_injp_4CD36E.bytes,      // [108] パスコード03
    (unsigned char*)s_injp_4CD376.bytes,      // [109] 植物学
    (unsigned char*)s_injp_4CD37D.bytes,      // [110] イングラム
    (unsigned char*)s_injp_4CD383.bytes,      // [111] ミニミ
    (unsigned char*)s_injp_4CD075.bytes,      // [112] クランク
    (unsigned char*)s_injp_4CD075.bytes,      // [113] クランク
    (unsigned char*)s_injp_4CD0C3.bytes,      // [114] 薬
    (unsigned char*)s_injp_4CD11C.bytes,      // [115] 館のカギ
    (unsigned char*)s_injp_4CD11C.bytes,      // [116] 館のカギ
    (unsigned char*)s_injp_4CD11C.bytes,      // [117] 館のカギ
    (unsigned char*)s_injp_4CD11C.bytes,      // [118] 館のカギ
    (unsigned char*)s_injp_4CD18C.bytes,      // [119] 研究所のカギ
    (unsigned char*)s_injp_4CD196.bytes,      // [120] スペシャルキー
    (unsigned char*)s_injp_4CD14B.bytes,      // [121] 寄宿舎のカギ
    (unsigned char*)s_injp_4CD14B.bytes,      // [122] 寄宿舎のカギ
    (unsigned char*)s_injp_4CD18C.bytes,      // [123] 研究所のカギ
    (unsigned char*)s_injp_4CD17F.bytes,      // [124] 小さなカギ
    (unsigned char*)s_injp_4CD19E.bytes,      // [125] 赤い本
    (unsigned char*)s_injp_4CD1AC.bytes,      // [126] 最後の書(下)
    (unsigned char*)s_injp_4CD1BA.bytes,      // [127] 最後の書(上)
};

// --------------------------------------------------------------------------
// g_UnknownItemNamePointersJpn (0x004CD548) - shown for unexamined items
// --------------------------------------------------------------------------
extern const unsigned char* g_UnknownItemNamePointersJpn[16] = {
    (unsigned char*)s_injp_4CD075.bytes,      // [  0] クランク
    (unsigned char*)s_injp_4CD075.bytes,      // [  1] クランク
    (unsigned char*)s_injp_4CD0C3.bytes,      // [  2] 薬
    (unsigned char*)s_injp_4CD11C.bytes,      // [  3] 館のカギ
    (unsigned char*)s_injp_4CD11C.bytes,      // [  4] 館のカギ
    (unsigned char*)s_injp_4CD11C.bytes,      // [  5] 館のカギ
    (unsigned char*)s_injp_4CD11C.bytes,      // [  6] 館のカギ
    (unsigned char*)s_injp_4CD18C.bytes,      // [  7] 研究所のカギ
    (unsigned char*)s_injp_4CD196.bytes,      // [  8] スペシャルキー
    (unsigned char*)s_injp_4CD14B.bytes,      // [  9] 寄宿舎のカギ
    (unsigned char*)s_injp_4CD14B.bytes,      // [ 10] 寄宿舎のカギ
    (unsigned char*)s_injp_4CD18C.bytes,      // [ 11] 研究所のカギ
    (unsigned char*)s_injp_4CD17F.bytes,      // [ 12] 小さなカギ
    (unsigned char*)s_injp_4CD19E.bytes,      // [ 13] 赤い本
    (unsigned char*)s_injp_4CD1AC.bytes,      // [ 14] 最後の書(下)
    (unsigned char*)s_injp_4CD1BA.bytes,      // [ 15] 最後の書(上)
};

// --------------------------------------------------------------------------
// g_ItemDescriptionsJpn (0x004C9370) - item viewer examine text
// --------------------------------------------------------------------------
static constexpr auto s_idjp_4C8E68 = STR_JP(u8"この装備だけで調査を\\n進めていくのはむずかしいだろう");
static constexpr auto s_idjp_4C8E89 = STR_JP(u8"ベレッタM92FSオートマチック\\n9mmパラベラム弾を撃ち出す自動銃だ");
static constexpr auto s_idjp_4C8EB4 = STR_JP(u8"レミントンM870\\nひろいレンジを攻撃できる銃だ");
static constexpr auto s_idjp_4C8ED1 = STR_JP(u8"357マグナム弾を撃ち出せる銃\\n強力だが、あつかいづらい");
static constexpr auto s_idjp_4C8EF5 = STR_JP(u8"燃料がMAXの時なら\\n8secは火炎を射出し続けられる");
static constexpr auto s_idjp_4C8F1A = STR_JP(u8"グレネード弾、火炎弾、硫酸弾\\nこれらの弾薬を射出できるランチャー");
static constexpr auto s_idjp_4C8F47 = STR_JP(u8"これならどんなヤツでも一撃だ");  // これならどんなヤツでも一撃だ
static constexpr auto s_idjp_4C8F59 = STR_JP(u8"ベレッタに用いるマガジンケースだ");  // ベレッタに用いるマガジンケースだ
static constexpr auto s_idjp_4C8F6C = STR_JP(u8"ショットガンに用いる弾");  // ショットガンに用いる弾
static constexpr auto s_idjp_4C8F7B = STR_JP(u8"マグナム弾より強力で危険な弾薬\\nコルトパイソンに使用できる");
static constexpr auto s_idjp_4C8FA3 = STR_JP(u8"357マグナム弾\\nコルトパイソンに使用できる");
static constexpr auto s_idjp_4C8FBE = STR_JP(u8"火炎放射器に用いる燃剤が入っている");  // 火炎放射器に用いる燃剤が入っている
static constexpr auto s_idjp_4C8FDA = STR_JP(u8"グレネードガン用の強力な弾薬");  // グレネードガン用の強力な弾薬
static constexpr auto s_idjp_4C8FEF = STR_JP(u8"薬剤を入れるためのガラスビンだ");  // 薬剤を入れるためのガラスビンだ
static constexpr auto s_idjp_4C9003 = STR_JP(u8"ビンの中に水が入っている");  // ビンの中に水が入っている
static constexpr auto s_idjp_4C9014 = STR_JP(u8"この薬からVーJOLTを成生できる");  // この薬からVーJOLTを成生できる
static constexpr auto s_idjp_4C902A = STR_JP(u8"これは必要とする薬ではない");  // これは必要とする薬ではない
static constexpr auto s_idjp_4C903C = STR_JP(u8"これでツタの化け物を倒す事が出来る");  // これでツタの化け物を倒す事が出来る
static constexpr auto s_idjp_4C9055 = STR_JP(u8"銃身が壊れていて装備すると危険だ\\n他の使い方でもあるのだろうか・・・");
static constexpr auto s_idjp_4C9083 = STR_JP(u8"すり合わせたようなキズ跡がついている\\n何かにはめこんだりするのだろうか");
static constexpr auto s_idjp_4C90AB = STR_JP(u8"美しく光りかがやいている");  // 美しく光りかがやいている
static constexpr auto s_idjp_4C90BB = STR_JP(u8"タイトルは『月光』とある");  // タイトルは『月光』とある
static constexpr auto s_idjp_4C90CD = STR_JP(u8"最後の書(下)に入っていたメダルだ\\n何か特別な使い方でもあるのだろうか?");
static constexpr auto s_idjp_4C90FF = STR_JP(u8"最後の書(上)に入っていたメダルだ\\n何か特別な使い方でもあるのだろうか?");
static constexpr auto s_idjp_4C9131 = STR_JP(u8"これでエレベータを動かす事が出来る");  // これでエレベータを動かす事が出来る
static constexpr auto s_idjp_4C9148 = STR_JP(u8"何かの起動用ディスクのようだ");  // 何かの起動用ディスクのようだ
static constexpr auto s_idjp_4C915C = STR_JP(u8"風をかたどった絵が刻まれている");  // 風をかたどった絵が刻まれている
static constexpr auto s_idjp_4C9170 = STR_JP(u8"これでブラッドに合図が出来る");  // これでブラッドに合図が出来る
static constexpr auto s_idjp_4C9184 = STR_JP(u8"研究レポートかなにかのようだが\\nこのままではよくわからない");
static constexpr auto s_idjp_4C91A5 = STR_JP(u8"月をかたどった絵が刻まれている");  // 月をかたどった絵が刻まれている
static constexpr auto s_idjp_4C91B9 = STR_JP(u8"星をかたどった絵が刻まれている");  // 星をかたどった絵が刻まれている
static constexpr auto s_idjp_4C91CD = STR_JP(u8"日をかたどった絵が刻まれている");  // 日をかたどった絵が刻まれている
static constexpr auto s_idjp_4C91E1 = STR_JP(u8"タイプライターなどで使用する物だ");  // タイプライターなどで使用する物だ
static constexpr auto s_idjp_4C91F6 = STR_JP(u8"オイルはまだのこっている");  // オイルはまだのこっている
static constexpr auto s_idjp_4C920E = STR_JP(u8"特に気になる所はない");  // 特に気になる所はない
static constexpr auto s_idjp_4C921D = STR_JP(u8"カギ開け用のツール\\n単純な構造のカギを開ける事が出来る");
static constexpr auto s_idjp_4C9244 = STR_JP(u8"これは制御室に入るためのカギだ");  // これは制御室に入るためのカギだ
static constexpr auto s_idjp_4C9259 = STR_JP(u8"キズを全てなおす事が出来る");  // キズを全てなおす事が出来る
static constexpr auto s_idjp_4C926C = STR_JP(u8"1回分しかない");  // 1回分しかない
static constexpr auto s_idjp_4C9277 = STR_JP(u8"この地方に自生しているハーブだ");  // この地方に自生しているハーブだ
static constexpr auto s_idjp_4C928C = STR_JP(u8"グリーンとレッドハーブを調合した物だ");  // グリーンとレッドハーブを調合した物だ
static constexpr auto s_idjp_4C92A3 = STR_JP(u8"グリーンハーブを2つ調合した物だ");  // グリーンハーブを2つ調合した物だ
static constexpr auto s_idjp_4C92B8 = STR_JP(u8"グリーンとブルーハーブを調合した物だ");  // グリーンとブルーハーブを調合した物だ
static constexpr auto s_idjp_4C92CF = STR_JP(u8"グリーン、ブルー、レッドの3つを\\n調合した物だ");
static constexpr auto s_idjp_4C92EB = STR_JP(u8"グリーンハーブを3つ調合した物だ");  // グリーンハーブを3つ調合した物だ
static constexpr auto s_idjp_4C9300 = STR_JP(u8"グリーンハーブ2つにブルーハーブを\\n調合した物だ");
static constexpr auto s_idjp_4C931D = STR_JP(u8"バッテリーはまだ生きている");  // バッテリーはまだ生きている
static constexpr auto s_idjp_4C932D = STR_JP(u8"イングラム Mー11\\nベレッタとおなじ9mm弾を使用する");
static constexpr auto s_idjp_4C934E = STR_JP(u8"フルオートで射撃できる\\nライトウェイトマシンガンだ");

unsigned char* g_ItemDescriptionsJpn[82] = {
    (unsigned char*)s_idjp_4C8E68.bytes,      // [  0] この装備だけで調査を / 進めていくのはむずかしいだろう
    (unsigned char*)s_idjp_4C8E89.bytes,      // [  1] ベレッタM92FSオートマチック / 9mmパラベラム弾を撃ち出す自動銃だ
    (unsigned char*)s_idjp_4C8EB4.bytes,      // [  2] レミントンM870 / ひろいレンジを攻撃できる銃だ
    (unsigned char*)s_idjp_4C8ED1.bytes,      // [  3] 357マグナム弾を撃ち出せる銃 / 強力だが、あつかいづらい
    (unsigned char*)s_idjp_4C8ED1.bytes,      // [  4] 357マグナム弾を撃ち出せる銃 / 強力だが、あつかいづらい
    (unsigned char*)s_idjp_4C8EF5.bytes,      // [  5] 燃料がMAXの時なら / 8secは火炎を射出し続けられる
    (unsigned char*)s_idjp_4C8F1A.bytes,      // [  6] グレネード弾、火炎弾、硫酸弾 / これらの弾薬を射出できるランチャー
    (unsigned char*)s_idjp_4C8F1A.bytes,      // [  7] グレネード弾、火炎弾、硫酸弾 / これらの弾薬を射出できるランチャー
    (unsigned char*)s_idjp_4C8F1A.bytes,      // [  8] グレネード弾、火炎弾、硫酸弾 / これらの弾薬を射出できるランチャー
    (unsigned char*)s_idjp_4C8F47.bytes,      // [  9] これならどんなヤツでも一撃だ
    (unsigned char*)s_idjp_4C8F59.bytes,      // [ 10] ベレッタに用いるマガジンケースだ
    (unsigned char*)s_idjp_4C8F6C.bytes,      // [ 11] ショットガンに用いる弾
    (unsigned char*)s_idjp_4C8F7B.bytes,      // [ 12] マグナム弾より強力で危険な弾薬 / コルトパイソンに使用できる
    (unsigned char*)s_idjp_4C8FA3.bytes,      // [ 13] 357マグナム弾 / コルトパイソンに使用できる
    (unsigned char*)s_idjp_4C8FBE.bytes,      // [ 14] 火炎放射器に用いる燃剤が入っている
    (unsigned char*)s_idjp_4C8FDA.bytes,      // [ 15] グレネードガン用の強力な弾薬
    (unsigned char*)s_idjp_4C8FDA.bytes,      // [ 16] グレネードガン用の強力な弾薬
    (unsigned char*)s_idjp_4C8FDA.bytes,      // [ 17] グレネードガン用の強力な弾薬
    (unsigned char*)s_idjp_4C8FEF.bytes,      // [ 18] 薬剤を入れるためのガラスビンだ
    (unsigned char*)s_idjp_4C9003.bytes,      // [ 19] ビンの中に水が入っている
    (unsigned char*)s_idjp_4C9014.bytes,      // [ 20] この薬からVーJOLTを成生できる
    (unsigned char*)s_idjp_4C9014.bytes,      // [ 21] この薬からVーJOLTを成生できる
    (unsigned char*)s_idjp_4C902A.bytes,      // [ 22] これは必要とする薬ではない
    (unsigned char*)s_idjp_4C902A.bytes,      // [ 23] これは必要とする薬ではない
    (unsigned char*)s_idjp_4C902A.bytes,      // [ 24] これは必要とする薬ではない
    (unsigned char*)s_idjp_4C902A.bytes,      // [ 25] これは必要とする薬ではない
    (unsigned char*)s_idjp_4C903C.bytes,      // [ 26] これでツタの化け物を倒す事が出来る
    (unsigned char*)s_idjp_4C9055.bytes,      // [ 27] 銃身が壊れていて装備すると危険だ / 他の使い方でもあるのだろうか・・・
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 28] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 29] 特に気になる所はない
    (unsigned char*)s_idjp_4C9083.bytes,      // [ 30] すり合わせたようなキズ跡がついている / 何かにはめこんだりするのだろうか
    (unsigned char*)s_idjp_4C9083.bytes,      // [ 31] すり合わせたようなキズ跡がついている / 何かにはめこんだりするのだろうか
    (unsigned char*)s_idjp_4C90AB.bytes,      // [ 32] 美しく光りかがやいている
    (unsigned char*)s_idjp_4C90AB.bytes,      // [ 33] 美しく光りかがやいている
    (unsigned char*)s_idjp_4C90BB.bytes,      // [ 34] タイトルは『月光』とある
    (unsigned char*)s_idjp_4C90CD.bytes,      // [ 35] 最後の書(下)に入っていたメダルだ / 何か特別な使い方でもあるのだろうか?
    (unsigned char*)s_idjp_4C90FF.bytes,      // [ 36] 最後の書(上)に入っていたメダルだ / 何か特別な使い方でもあるのだろうか?
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 37] 特に気になる所はない
    (unsigned char*)s_idjp_4C9131.bytes,      // [ 38] これでエレベータを動かす事が出来る
    (unsigned char*)s_idjp_4C9148.bytes,      // [ 39] 何かの起動用ディスクのようだ
    (unsigned char*)s_idjp_4C915C.bytes,      // [ 40] 風をかたどった絵が刻まれている
    (unsigned char*)s_idjp_4C9170.bytes,      // [ 41] これでブラッドに合図が出来る
    (unsigned char*)s_idjp_4C9184.bytes,      // [ 42] 研究レポートかなにかのようだが / このままではよくわからない
    (unsigned char*)s_idjp_4C91A5.bytes,      // [ 43] 月をかたどった絵が刻まれている
    (unsigned char*)s_idjp_4C91B9.bytes,      // [ 44] 星をかたどった絵が刻まれている
    (unsigned char*)s_idjp_4C91CD.bytes,      // [ 45] 日をかたどった絵が刻まれている
    (unsigned char*)s_idjp_4C91E1.bytes,      // [ 46] タイプライターなどで使用する物だ
    (unsigned char*)s_idjp_4C91F6.bytes,      // [ 47] オイルはまだのこっている
    (unsigned char*)s_idjp_4C921D.bytes,      // [ 48] カギ開け用のツール / 単純な構造のカギを開ける事が出来る
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 49] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 50] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 51] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 52] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 53] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 54] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 55] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 56] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 57] 特に気になる所はない
    (unsigned char*)s_idjp_4C9244.bytes,      // [ 58] これは制御室に入るためのカギだ
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 59] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 60] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 61] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 62] 特に気になる所はない
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 63] 特に気になる所はない
    (unsigned char*)s_idjp_4C9259.bytes,      // [ 64] キズを全てなおす事が出来る
    (unsigned char*)s_idjp_4C926C.bytes,      // [ 65] 1回分しかない
    (unsigned char*)s_idjp_4C9277.bytes,      // [ 66] この地方に自生しているハーブだ
    (unsigned char*)s_idjp_4C9277.bytes,      // [ 67] この地方に自生しているハーブだ
    (unsigned char*)s_idjp_4C9277.bytes,      // [ 68] この地方に自生しているハーブだ
    (unsigned char*)s_idjp_4C928C.bytes,      // [ 69] グリーンとレッドハーブを調合した物だ
    (unsigned char*)s_idjp_4C92A3.bytes,      // [ 70] グリーンハーブを2つ調合した物だ
    (unsigned char*)s_idjp_4C92B8.bytes,      // [ 71] グリーンとブルーハーブを調合した物だ
    (unsigned char*)s_idjp_4C92CF.bytes,      // [ 72] グリーン、ブルー、レッドの3つを / 調合した物だ
    (unsigned char*)s_idjp_4C92EB.bytes,      // [ 73] グリーンハーブを3つ調合した物だ
    (unsigned char*)s_idjp_4C9300.bytes,      // [ 74] グリーンハーブ2つにブルーハーブを / 調合した物だ
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 75] 特に気になる所はない
    (unsigned char*)s_idjp_4C931D.bytes,      // [ 76] バッテリーはまだ生きている
    (unsigned char*)s_idjp_4C932D.bytes,      // [ 77] イングラム Mー11 / ベレッタとおなじ9mm弾を使用する
    (unsigned char*)s_idjp_4C934E.bytes,      // [ 78] フルオートで射撃できる / ライトウェイトマシンガンだ
    // CUSTOM - ITEM_GRENADE_PISTOL - kept in sync with the +1 entry appended
    // to g_ItemDescriptions (Globals.cpp), since set_item_description_message
    // (RoomInit.cpp) bounds-checks both tables against g_ItemDescriptions's
    // size. No Japanese text was written for this mod item - reuse the
    // existing generic "nothing particularly noteworthy" filler used
    // elsewhere in this table for items without a unique description. This
    // row is unreachable in the USA/PC build this mod targets (JPN table is
    // only read when GetAssetVersion() selects the Biohazard asset tree).
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 79] 特に気になる所はない
    // CUSTOM - ITEM_ACID_PISTOL - the second appended entry, same filler and
    // the same reason as [79] above.
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 80] 特に気になる所はない
    // CUSTOM - ITEM_FREEZE_PISTOL - the third.
    (unsigned char*)s_idjp_4C920E.bytes,      // [ 81] 特に気になる所はない
};

